// This file is generated by scripts/generate-openapi.js. Do not edit manually.

export type ApiResponse<T = unknown> = {
  code: number
  message: string
  data: T
}

export type PaginatedData<T> = {
  list: T[]
  total: number
  page: number
  page_size: number
}

export type components = {
  schemas: {
    LoginPayload: {
      code: string
      platform: 'wechat' | 'douyin'
    }
    LoginResult: {
      token: string
      uid: string
      nickname: string
      avatar: string
      is_new: boolean
      need_bind_phone: boolean
      phone: string
    }
    ProfileUpdatePayload: {
      nickname: string
      avatar: string
    }
    CoupleInfo: {
      id: string
      user1_id: string
      user2_id: string
      status: string
    }
    BuddyGroup: {
      id: string
      name: string
      owner_id: string
      max_member: number
      status: string
      created_at: string
    }
    BuddyMember: {
      id: string
      group_id: string
      user_id: string
      role: 'owner' | 'admin' | 'member'
      joined_at: string
    }
    User: {
      uid: string
      nickname: string
      avatar: string
      points: number
      has_wx: boolean
      has_dy: boolean
      phone: string
      has_phone: boolean
      couple: components['schemas']['CoupleInfo'] | null
      buddy_groups: components['schemas']['BuddyGroup'][]
      created_at: string
    }
    InviteResult: {
      code: string
      expires_at: string
    }
    BuddyGroupSummary: {
      id: string
      name: string
    }
    CreateBuddyGroupPayload: {
      name: string
    }
    JoinInvitePayload: {
      code: string
    }
    TableMember: {
      id: string
      table_id: string
      user_id: string
      role: 'owner' | 'admin' | 'member'
      status: string
      joined_at: string
    }
    Table: {
      id: string
      type: 'personal' | 'couple' | 'buddy'
      name: string
      owner_id: string
      status: string
      created_at: string
      updated_at: string
      members: components['schemas']['TableMember'][]
    }
    RenameTablePayload: {
      name: string
    }
    Ingredient: {
      name: string
      amount: string
    }
    Step: {
      order: number
      description: string
      image?: string
    }
    Dish: {
      id: string
      owner_id: string
      table_id: string
      dish_type: 'dish' | 'takeout' | 'dineout'
      name: string
      category: string
      difficulty: number | null
      duration: number
      price: number | null
      ingredients: components['schemas']['Ingredient'][] | null
      steps: components['schemas']['Step'][] | null
      photos: string[] | null
      tags: string[]
      restaurant: string
      restaurant_note: string
      source: 'manual' | 'plaza'
      is_deleted: boolean
      created_at: string
      updated_at: string
    }
    DishPayload: {
      table_id: string
      dish_type: 'dish' | 'takeout' | 'dineout'
      name: string
      category?: string
      difficulty?: number | null
      duration?: number
      price?: number | null
      ingredients?: components['schemas']['Ingredient'][]
      steps?: components['schemas']['Step'][]
      photos?: string[]
      tags?: string[]
      restaurant?: string
      restaurant_note?: string
    }
    DishUpdatePayload: Partial<Omit<components['schemas']['DishPayload'], 'table_id' | 'dish_type'>>
    ImportDishPayload: {
      plaza_id: string
      table_id: string
    }
    PlazaDish: {
      id: string
      name: string
      category: string
      difficulty: number | null
      duration: number
      ingredients: components['schemas']['Ingredient'][] | null
      steps: components['schemas']['Step'][] | null
      photos: string[] | null
      tags: string[]
      import_count: number
      created_at: string
    }
    OrderItem: {
      id: string
      order_id: string
      dish_id: string
      dish_name?: string
      quantity: number
      unit_price: number | null
      confirmed_amount: number | null
    }
    OrderParticipant: {
      id: string
      order_id: string
      user_id: string
      status: 'invited' | 'accepted' | 'rejected' | 'skipped'
      created_at: string
      updated_at: string
    }
    Order: {
      id: string
      creator_id: string
      table_id: string
      dine_mode: 'together' | 'solo'
      status: 'pending' | 'confirmed' | 'rejected' | 'cancelled' | 'voted'
      total_amount: number | null
      vote_deadline?: string | null
      calendar_record_id?: string | null
      order_items: components['schemas']['OrderItem'][]
      participants?: components['schemas']['OrderParticipant'][]
      created_at: string
    }
    OrderVote: {
      id: string
      order_id: string
      user_id: string
      vote: 'approve' | 'reject' | 'skip'
      created_at: string
    }
    OrderItemPayload: {
      dish_id: string
      quantity: number
      confirmed_amount: number | null
    }
    OrderBasketItemPayload: {
      name: string
      quantity: string
    }
    CreateOrderPayload: {
      table_id: string
      dine_mode: 'solo' | 'together'
      participant_ids?: string[]
      items: components['schemas']['OrderItemPayload'][]
      basket_items?: components['schemas']['OrderBasketItemPayload'][]
    }
    VoteOrderPayload: {
      vote: 'approve' | 'reject' | 'skip'
    }
    OrderVotes: {
      approve: number
      reject: number
      skip: number
      total: number
      votes?: components['schemas']['OrderVote'][]
    }
    RecordPhoto: {
      id: string
      record_id: string
      url: string
      type: string
      sort_order: number
    }
    RecordComment: {
      id: string
      record_id: string
      user_id: string
      content: string
      created_at: string
    }
    CalendarOrderItem: {
      id: string
      dish_id: string
      dish_name: string
      quantity: number
      unit_price: number | null
      confirmed_amount: number | null
    }
    CalendarOrder: {
      id: string
      items: components['schemas']['CalendarOrderItem'][]
    }
    CalendarRecord: {
      id: string
      user_id: string
      table_id: string
      record_date: string
      meal_type: string
      meal_period: string
      dish_ids: string[]
      restaurant: string
      amount: number | null
      source: string
      status: string
      photos: components['schemas']['RecordPhoto'][]
      comments: components['schemas']['RecordComment'][]
      order?: components['schemas']['CalendarOrder'] | null
      created_at: string
    }
    PhotoPayload: {
      url: string
      type: string
    }
    CalendarRecordPayload: {
      table_id: string
      record_date: string
      meal_type: string
      meal_period?: string
      dish_ids?: string[]
      restaurant?: string
      amount?: number | null
      photos?: components['schemas']['PhotoPayload'][]
      content?: string
    }
    CalendarRecordUpdateOrderItem: {
      id: string
      confirmed_amount: number | null
    }
    CalendarRecordUpdatePayload: {
      meal_type?: string
      meal_period?: string
      restaurant?: string
      amount?: number | null
      order_items?: components['schemas']['CalendarRecordUpdateOrderItem'][]
    }
    MonthlyStats: {
      total_amount: number
      meal_count: Record<string, number>
      total_records: number
      unrecorded_days: string[]
      year: number
      month: number
    }
    WishItem: {
      id: string
      user_id: string
      table_id: string
      name: string
      note: string
      dish_id: string | null
      is_completed: boolean
      created_at: string
    }
    CreateWishPayload: {
      table_id: string
      name: string
      note?: string
      dish_id?: string | null
    }
    CheckinStatus: {
      today_checked: boolean
      month_count: number
      streak: number
    }
    CheckinResult: {
      points?: number
      checkin_date?: string
      today_checked?: boolean
      month_count?: number
      streak?: number
    }
    BasketItem: {
      id: string
      user_id: string
      table_id: string
      name: string
      quantity: string
      is_purchased: boolean
      created_at: string
    }
    BasketPayload: {
      table_id: string
      name: string
      quantity?: string
    }
    BudgetSetting: {
      id: string
      user_id: string
      table_id: string
      month: string
      budget: number
      spent?: number
      created_at?: string
      updated_at?: string
    }
    BudgetPayload: {
      table_id: string
      month: string
      budget: number
    }
    PointRecord: {
      id: string
      user_id: string
      points: number
      reason: string
      created_at: string
    }
  }
}

export type operations = {
  authLogin: {
    requestBody: components['schemas']['LoginPayload']
    response: ApiResponse<components['schemas']['LoginResult']>
  }
  getProfile: {
    response: ApiResponse<components['schemas']['User']>
  }
  updateProfile: {
    requestBody: components['schemas']['ProfileUpdatePayload']
    response: ApiResponse<void>
  }
  bindPhone: {
    requestBody: { phone: string }
    response: ApiResponse<void>
  }
  createCoupleInvite: {
    response: ApiResponse<components['schemas']['InviteResult']>
  }
  joinCouple: {
    requestBody: components['schemas']['JoinInvitePayload']
    response: ApiResponse<void>
  }
  createBuddyGroup: {
    requestBody: components['schemas']['CreateBuddyGroupPayload']
    response: ApiResponse<components['schemas']['BuddyGroupSummary']>
  }
  createBuddyInvite: {
    response: ApiResponse<components['schemas']['InviteResult']>
  }
  joinBuddyGroup: {
    requestBody: components['schemas']['JoinInvitePayload']
    response: ApiResponse<void>
  }
  removeBuddyMember: {
    response: ApiResponse<void>
  }
  listTables: {
    response: ApiResponse<components['schemas']['Table'][]>
  }
  renameTable: {
    requestBody: components['schemas']['RenameTablePayload']
    response: ApiResponse<components['schemas']['Table']>
  }
  listDishes: {
    parameters: {
      query: {
        table_id: string
        dish_type?: string
        category?: string
        keyword?: string
        page?: number
        page_size?: number
      }
    }
    response: ApiResponse<PaginatedData<components['schemas']['Dish']>>
  }
  getDish: {
    response: ApiResponse<components['schemas']['Dish']>
  }
  createDish: {
    requestBody: components['schemas']['DishPayload']
    response: ApiResponse<components['schemas']['Dish']>
  }
  updateDish: {
    requestBody: components['schemas']['DishUpdatePayload']
    response: ApiResponse<void>
  }
  deleteDish: {
    response: ApiResponse<void>
  }
  importDish: {
    requestBody: components['schemas']['ImportDishPayload']
    response: ApiResponse<components['schemas']['Dish']>
  }
  searchPlaza: {
    parameters: {
      query: {
        category?: string
        keyword?: string
        page?: number
        page_size?: number
      }
    }
    response: ApiResponse<PaginatedData<components['schemas']['PlazaDish']>>
  }
  getPlazaCategories: {
    response: ApiResponse<string[]>
  }
  listOrders: {
    parameters: {
      query: {
        table_id: string
        status?: string
        page?: number
        page_size?: number
      }
    }
    response: ApiResponse<PaginatedData<components['schemas']['Order']>>
  }
  getOrder: {
    response: ApiResponse<components['schemas']['Order']>
  }
  createOrder: {
    requestBody: components['schemas']['CreateOrderPayload']
    response: ApiResponse<components['schemas']['Order']>
  }
  confirmOrder: {
    response: ApiResponse<void>
  }
  rejectOrder: {
    response: ApiResponse<void>
  }
  cancelOrder: {
    response: ApiResponse<void>
  }
  voteOrder: {
    requestBody: components['schemas']['VoteOrderPayload']
    response: ApiResponse<void>
  }
  getOrderVotes: {
    response: ApiResponse<components['schemas']['OrderVotes']>
  }
  listCalendarRecords: {
    parameters: {
      query: {
        table_id: string
        year?: number
        month?: number
      }
    }
    response: ApiResponse<components['schemas']['CalendarRecord'][]>
  }
  listCalendarRecordsByDate: {
    parameters: {
      query: {
        table_id: string
        date: string
      }
    }
    response: ApiResponse<components['schemas']['CalendarRecord'][]>
  }
  getCalendarRecord: {
    response: ApiResponse<components['schemas']['CalendarRecord']>
  }
  createCalendarRecord: {
    requestBody: components['schemas']['CalendarRecordPayload']
    response: ApiResponse<components['schemas']['CalendarRecord']>
  }
  updateCalendarRecord: {
    requestBody: components['schemas']['CalendarRecordUpdatePayload']
    response: ApiResponse<void>
  }
  deleteCalendarRecord: {
    response: ApiResponse<void>
  }
  addRecordComment: {
    requestBody: { content: string }
    response: ApiResponse<components['schemas']['RecordComment']>
  }
  addRecordPhoto: {
    requestBody: components['schemas']['PhotoPayload']
    response: ApiResponse<components['schemas']['RecordPhoto']>
  }
  getMonthlyStats: {
    parameters: {
      query: {
        table_id: string
        year?: number
        month?: number
      }
    }
    response: ApiResponse<components['schemas']['MonthlyStats']>
  }
  listWishes: {
    parameters: {
      query: {
        table_id: string
        completed?: boolean
      }
    }
    response: ApiResponse<components['schemas']['WishItem'][]>
  }
  createWish: {
    requestBody: components['schemas']['CreateWishPayload']
    response: ApiResponse<components['schemas']['WishItem']>
  }
  completeWish: {
    response: ApiResponse<void>
  }
  deleteWish: {
    response: ApiResponse<void>
  }
  checkin: {
    response: ApiResponse<components['schemas']['CheckinResult']>
  }
  getCheckinStatus: {
    response: ApiResponse<components['schemas']['CheckinStatus']>
  }
  listBasket: {
    parameters: {
      query: {
        table_id: string
      }
    }
    response: ApiResponse<components['schemas']['BasketItem'][]>
  }
  addToBasket: {
    requestBody: components['schemas']['BasketPayload']
    response: ApiResponse<components['schemas']['BasketItem']>
  }
  toggleBasket: {
    response: ApiResponse<void>
  }
  deleteBasket: {
    response: ApiResponse<void>
  }
  getBudget: {
    parameters: {
      query: {
        table_id: string
        month: string
      }
    }
    response: ApiResponse<components['schemas']['BudgetSetting']>
  }
  setBudget: {
    requestBody: components['schemas']['BudgetPayload']
    response: ApiResponse<components['schemas']['BudgetSetting']>
  }
  getPointHistory: {
    parameters: {
      query: {
        page?: number
        page_size?: number
      }
    }
    response: ApiResponse<PaginatedData<components['schemas']['PointRecord']>>
  }
}
